import React from 'react';
import { Link } from 'react-router-dom';
import Header from '../components/layout/Header';
import Footer from '../components/layout/Footer';

const PrivacyPage: React.FC = () => {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <Header />
      
      <main className="flex-1">
        <div className="page-header bg-slate-50 py-12">
          <div className="container mx-auto px-4">
            <h1 className="page-title text-3xl font-bold text-center">Privacy Policy</h1>
            <p className="text-slate-600 max-w-3xl mx-auto text-center">
              Your privacy is important to us. This policy explains how we collect, use, disclose, and safeguard your information.
            </p>
          </div>
        </div>

        <div className="content-section py-12">
          <div className="container mx-auto px-4">
            <div className="privacy-content max-w-4xl mx-auto">
              <div className="mb-8">
                <p className="text-sm text-slate-500 mb-4">Last Updated: April 1, 2023</p>
                
                <p className="mb-4">
                  HealthInsightToday ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by HealthInsightToday.
                </p>
                
                <p className="mb-4">
                  This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, HealthInsightToday. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                </p>
              </div>

              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4">Definitions and Key Terms</h2>
                <p className="mb-4">
                  For this Privacy Policy:
                </p>
                <ul className="list-disc pl-8 mb-4 space-y-2">
                  <li><strong>Cookie:</strong> A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.</li>
                  <li><strong>Company:</strong> When this policy mentions "Company," "we," "us," or "our," it refers to HealthInsightToday that is responsible for your information under this Privacy Policy.</li>
                  <li><strong>Country:</strong> Where HealthInsightToday or the owners/founders of HealthInsightToday are based, in this case is the United States.</li>
                  <li><strong>Customer:</strong> Refers to the company, organization, or person that signs up to use the HealthInsightToday Service.</li>
                  <li><strong>Device:</strong> Any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit HealthInsightToday and use the services.</li>
                  <li><strong>Personal Data:</strong> Any information that directly, indirectly, or in connection with other information allows for the identification of a natural person.</li>
                  <li><strong>Service:</strong> Refers to the website, application, and the HealthInsightToday services provided by the Company.</li>
                  <li><strong>Third-party service:</strong> Refers to advertisers, sponsors, partners, and other third parties that provide data, content, or services for the HealthInsightToday platform.</li>
                </ul>
              </div>

              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4">Information We Collect</h2>
                <p className="mb-4">
                  We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey, or fill out a form.
                </p>
                
                <h3 className="text-xl font-bold mb-3">Personal Data</h3>
                <p className="mb-4">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
                <ul className="list-disc pl-8 mb-4 space-y-2">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                  <li>Cookies and Usage Data</li>
                  <li>Health data and medical records you choose to share</li>
                </ul>
                
                <h3 className="text-xl font-bold mb-3">Health Information</h3>
                <p className="mb-4">When you upload medical reports or lab results, we collect health information to provide you with our analysis and recommendation services. This information is handled with the highest level of confidentiality and in compliance with HIPAA regulations.</p>
              </div>

              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4">How We Use Your Information</h2>
                <p className="mb-4">We use the information we collect in various ways, including to:</p>
                <ul className="list-disc pl-8 mb-4 space-y-2">
                  <li>Provide, operate, and maintain our website and services</li>
                  <li>Analyze your health data to provide personalized insights</li>
                  <li>Improve, personalize, and expand our website and services</li>
                  <li>Understand and analyze how you use our website</li>
                  <li>Develop new products, services, features, and functionality</li>
                  <li>Communicate with you about our services</li>
                  <li>Process your transactions</li>
                  <li>Send you emails and updates</li>
                  <li>Find and prevent fraud</li>
                </ul>
              </div>

              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4">HIPAA Compliance</h2>
                <p className="mb-4">
                  As a platform that processes health information, we adhere to the Health Insurance Portability and Accountability Act (HIPAA). This means:
                </p>
                <ul className="list-disc pl-8 mb-4 space-y-2">
                  <li>We implement strong technical safeguards to protect your health information</li>
                  <li>We limit access to your health data to only those employees who need it to perform their job functions</li>
                  <li>We regularly train our staff on privacy and security protocols</li>
                  <li>We maintain appropriate administrative, physical, and technical procedures to protect your information</li>
                </ul>
              </div>

              <div className="mb-8">
                <h2 className="text-2xl font-bold mb-4">Contact Us</h2>
                <p className="mb-4">
                  If you have any questions about this Privacy Policy, please contact us:
                </p>
                <ul className="list-none mb-4">
                  <li>By email: <a href="mailto:privacy@healthinsighttoday.com" className="text-indigo-600 hover:underline">privacy@healthinsighttoday.com</a></li>
                  <li>By phone: <a href="tel:+18005551234" className="text-indigo-600 hover:underline">1-800-555-1234</a></li>
                </ul>
                <p>
                  <Link to="/contact" className="text-indigo-600 hover:underline">Visit our contact page</Link> for more ways to reach us.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default PrivacyPage; 